default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rockstar2_development
  username: rockstar2
  password: tu_password
  host: localhost
  port: 5432

test:
  <<: *default
  database: rockstar2_test
  username: rockstar2
  password: tu_password
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: rockstar2_production
    username: rockstar2
    password: <%= ENV["ROCKSTAR2_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: rockstar2_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: rockstar2_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: rockstar2_production_cable
    migrations_paths: db/cable_migrate

